### ISSUE TITLE
Add User Account page

### ISSUE THREAD

**Issue by charliealbright** [WilsonWillson/BracketMaster#28]
Functionality should include:

* password change/reset
* username change
* view owned tournaments
* view participating tournaments (?)
* possibly more as we see fit

Navigation to this page will replace "search" in the FloatingActionButton menu on the main page.

Need to check if Firebase supports pulling Tournaments based on owner

**Comment by aryamccarthy** [comment]
I think this would make sense to replace the Main page—rather than listing every available activity in the database, take you straight into a tailored view listing owned and participating tournaments. (Different color or a TabView to indicate whether owner or participant).

User and pass change should be quick and easy.

Firebase does support pulling Tournaments by owner. Envision it like any other database.

On Nov 20, 2015, at 11:58 AM, Charlie Albright <notifications@github.com<mailto:notifications@github.com>> wrote:


Functionality should include:

  *   password change/reset
  *   username change
  *   view owned tournaments
  *   view participating tournaments (?)
  *   possibly more as we see fit

Navigation to this page will replace "search" in the FloatingActionButton menu on the main page.

Need to check if Firebase supports pulling Tournaments based on owner

**Comment by charliealbright** [comment]
I'm not sure it should replace the main page....but I agree with having a 2 or 3-tab view with "account", "my tournaments", etc. That would be really clean.

**Comment by aryamccarthy** [comment]
Done.
